#!/bin/bash

audioDir=/Users/zacklee/Documents/animu/audio 
currDir=$(basename "$1")
currDir=$(echo $currDir | sed "s/([^()]*)//g" | sed -e 's/\[[^][]*\]//g')  

# currDir="${currDir//[^[:ascii:]]/}"
mkdir -p "${audioDir}/${currDir}"
mkdir -p "${audioDir}/${currDir}/splits"
find -E "$1" -regex ".*\.(avi|mov|mkv|mp4)" | while read file; do
	if [ -f "$file" ]; then 
		currFile=$(basename $file)
		echo 'splitting------------------------------------------------------------'
		
		# remove parenthesis, braces
		currFile=$(echo $currFile | sed "s/([^()]*)//g" | sed -e 's/\[[^][]*\]//g')  
		# remove file extension
		currFile=${currFile%.*}
		echo $currFile

		newFile="${audioDir}/${currDir}/${currFile}.mp3"

		ffmpeg -i "$file" -vn -acodec libmp3lame -ac 2 -ab 160k -ar 48000 "$newFile" < /dev/null

		ffmpeg -i "$newFile" -f segment -segment_time 180 -c copy \
		"${audioDir}/${currDir}/splits/${currFile}%03d.mp3" < /dev/null

		echo '------------------------------------------------------------end'
		# break
	fi
done













